name: navigation
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.5.0

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  main_page_view:
    path: ../features/main_page_view


dev_dependencies:
  flutter_lints: 2.0.1
  dart_code_metrics: ^5.7.5
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
