name: food_delivery_app
description: A new Flutter project.

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  navigation:
    path: ./navigation
  main_page_view:
    path: ./features/main_page_view
  shopping_cart:
    path: ./features/shopping_cart
  settings:
    path: ./features/settings
  auth:
    path: ./features/auth
  order_history:
    path: ./features/order_history

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  rive: ^0.11.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: 'assets/image/logo.png'
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/rive_icons/home_icon.riv
    - assets/image/rive_icons/shapes.riv
    - assets/image/rive_icons/logo.riv
    - assets/image/rive_icons/empty_shopping_cart.riv
    - assets/image/rive_icons/empty_order_history.riv
    - assets/image/rive_icons/shopping_cart_banner.riv
    - assets/image/rive_icons/nothing_in_category.riv
    - assets/languages/en.json
    - assets/languages/es.json

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
