name: settings
description: Settings module
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core_ui:
    path: ../../core_ui
  core:
    path: ../../core
  domain:
    path: ../../domain
  main_page_view:
    path: ../main_page_view

  flutter_svg: ^2.0.6
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
