// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;


import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkLAByUZFSTUw_dkU8tqoaum5RFjlDOvA',
    appId: '1:903410526273:android:cae33361371e0711457ec0',
    messagingSenderId: '903410526273',
    projectId: 'food-delivery-app-31f05',
    storageBucket: 'food-delivery-app-31f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUae9r1RrK5ph-cGG97Spds0XfCNEr4o',
    appId: '1:903410526273:ios:7972839440872f51457ec0',
    messagingSenderId: '903410526273',
    projectId: 'food-delivery-app-31f05',
    storageBucket: 'food-delivery-app-31f05.appspot.com',
    androidClientId: '903410526273-airt70db6ngjcaflnhmo9hn6gpuuu9hk.apps.googleusercontent.com',
    iosClientId: '903410526273-fek7ks6tqskd8e6bpjrkc6a1pvkiuo58.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}
